In [135]:
import numpy as np
from pulp import *#library for lienar programming in Python

In [136]:
#Problem in brief
#solution for Banner Chemicals
#Total capacity of the plant=110
#The plant produces HIGH and SUPREME grade
#Profit from High and Supreme is 80 & 200 repectivley.
#Ingredient A & B are used to make both High and Supreme
#3 and 1 is the qty of A required to procude High & Supreme resp.
#2 and 3 is the qty of B required to produce High & Supreme resp.
# total of 300 & 280 is available of A and B

# simple way to Solve---Full Notation

In [137]:
#formulating the given parameters
Capacity=110
Products=['High','Supreme']
Profits=[80,200]
Ingredients=['A','B']
High=[3,1]
Supreme=[2,3]
Ingredients_Capacity=[300,280]

In [138]:
#pulp.pulpTestAll()--> PULP_CBC_CMD passed

In [139]:
# defines the problem
prob = LpProblem("problem", LpMaximize)

# declare your variables
x1 = LpVariable("x1",lowBound=0,upBound=None)# 0<= x1
x2 = LpVariable("x2",lowBound=0,upBound=None) # 0<= x2

# defines the objective function to maximize
prob += (x1*Profits[0]+x2*Profits[1]) # max(x1*80+x2*200)

# defines the constraints
prob += x1+x2<= 110   #(x1+x2<=110) capacity constraint
prob += 3*x1+2*x2<=300  # 3*x1+2*x2<=300 # Ingredient A constraint
prob += 1*x1+3*x2<=280  #1*x1+3*x2<=280 #Ingredient B constraint

# solve the problem
status = prob.solve()
LpStatus[status]

# print the results
print (x1.varValue)
print (x2.varValue)
print (value(prob.objective))
print ('\n')
print(prob)
LpStatus[prob.status]#to verify the results

25.0
85.0
19000.0


problem:
MAXIMIZE
80*x1 + 200*x2 + 0
SUBJECT TO
_C1: x1 + x2 <= 110

_C2: 3 x1 + 2 x2 <= 300

_C3: x1 + 3 x2 <= 280

VARIABLES
x1 Continuous
x2 Continuous



'Optimal'

# using Sigma Notation

In [140]:
#now let us attemt the same by using sigma notation in the codes 
#this way we can scale up the problem easily

In [141]:
#formulating the given parameters
Capacity=110
Products=['High','Supreme']
Profits=[80,200]
Ingredients=['A','B']
High=[3,1]
Supreme=[2,3]
Ingredients_Capacity=[300,280]

In [207]:
# defines the problem
prob2 = LpProblem("problem", LpMaximize)

# declare your variables
x=LpVariable.dicts("decvars",Products,lowBound=0,upBound=None)#decision variable
#is created for each index of Products

# defines the objective function to maximize
prob2+= lpSum([Profits[i]*x.values()[i] for i in range(len(Products))])
# max(x1*80+x2*200)

# defines the constraints
prob2 += lpSum(x.values())<= 110   #(x1+x2<=110) capacity constraint

prob2 +=lpSum(x.values()[0]*High[0]+x.values()[1]*Supreme[0])<=Ingredients_Capacity[0]
#3*x1+2*x2<=300 #Ingredient A constraint
prob2 +=lpSum(x.values()[0]*High[1]+x.values()[1]*Supreme[1])<=Ingredients_Capacity[1]
#1*x1+3*x2<=280 #Ingredient B constraint


# solve the problem
status = prob2.solve()
LpStatus[status]

'Optimal'

In [208]:
# print the results
#print value(x.values())
print (value(prob2.objective))
print ('\n')
for i in range(2):
    print x.values()[i].varValue
print ('\n')
print(prob2)

19000.0


25.0
85.0


problem:
MAXIMIZE
80*decvars_High + 200*decvars_Supreme + 0
SUBJECT TO
_C1: decvars_High + decvars_Supreme <= 110

_C2: 3 decvars_High + 2 decvars_Supreme <= 300

_C3: decvars_High + 3 decvars_Supreme <= 280

VARIABLES
decvars_High Continuous
decvars_Supreme Continuous



In [184]:
p1=np.array(x)
print p1
p3=[2,3]

{'High': decvars_High, 'Supreme': decvars_Supreme}


In [183]:
p2=np.array([High,Supreme])
print p2

[[3 1]
 [2 3]]


In [195]:
np.dot(p2,p3)<=np.array([1,2])

array([False, False], dtype=bool)

In [196]:
np.array([1,2])

array([1, 2])